### ISSUE TITLE
theorangealliance.net redirects to an ip?

### ISSUE THREAD

**Issue by joeybab3** [JuicyData/TheOrangeAlliance2016-2017#31]
I'm assuming you're aware of this but in case you aren't, http://theorangealliance.net redirects to an ip address instead of the .tk domain.

**Comment by CameronDeMille** [comment]
Yeah I got rid of the dot.tk domain. I am trying to figure out how to do dns masking with the current domain right now. The goal is to have theorangealliance.net redirect to theorangealliance.net:8080.

**Comment by joeybab3** [comment]
lmk if you need help with that, what registrar did you use for theorangealliance.net?

**Comment by CameronDeMille** [comment]
I used google domains. I can only get it to do either url forwarding or dns masking. I cant get it to do both.
