### ISSUE TITLE
HTML References are not relative

### ISSUE THREAD

**Issue by MichaelLeonffu** [JuicyData/TheOrangeAlliance2016-2017#6]
HTML references are **not** relative in several files:
````html
<a class="nav-brand" href="http://theorangealliance.tk:8080/">
````
another example:
````html
<a href = "http://theorangealliance.tk:8080/events/velocity-vortex.php">Events</a>
````

This means that clicking on the links will send to the official site than a local installation.

@TheOrangeAllianceNet/frontend

**Comment by CameronDeMille** [comment]
Tried to fix all of the links but now the entire website is broken.
